# space-separated list of file extensions interpreted as zip-compatible files
org.javatb.search.zip.extensions = zip jar war ear rar pak ods odp odg odt

# max history size of the persisted field values (file pattern and search term)
# this is the max number of items in the popup window that lists previously used values.
org.javatb.history.size = 10

###
### Configuration of the view displaying the search results
### This is the fqn of a class implementing the interface
### 'org.javatb.search.ui.results.ResultRenderer'
###
# table with sortable path, size, compressed size, last updated and attributes columns
org.javatb.renderer.class = org.javatb.search.ui.results.TableResultRenderer
# list of file paths
#org.javatb.renderer.class = org.javatb.search.ui.results.ListResultRenderer
